import { generateKeyPairSync } from "node:crypto";
import { describe, expect, it } from "vitest";
import { createIndependentQualityAttestation, sha256Json } from "../../../scripts/lib/independent-quality-attestation.mjs";
import { createTrustedAuditorKey } from "./SignedExternalTrustAnchor";
import { createTrustedAuditorKeyRegistry, registerTrustedAuditorKey, rotateTrustedAuditorKey, revokeTrustedAuditorKey } from "./TrustedAuditorKeyRegistry";
import { createSignedIndependentQualityAttestation, verifySignedIndependentQualityAttestation } from "./SignedIndependentQualityAttestation";

const COMMIT="c".repeat(40);
const report=()=>({schema:"goodle.independent-quality-gate-report.v1",gate:"M70",status:"PASS",git:{commit_sha:COMMIT,tracked_dirty:false},runtime:{node:"v24.18.0",npm:"11.16.0",platform:"win32",arch:"x64"},steps:[{command:"npm test",exit_code:0,signal:null,status:"PASS"},{command:"npm run check",exit_code:0,signal:null,status:"PASS"},{command:"npm run build",exit_code:0,signal:null,status:"PASS"}]});
function fixture(){const quality_report=report();const report_sha256=sha256Json(quality_report);const quality_attestation=createIndependentQualityAttestation({report:quality_report,reportSha256:report_sha256,expectedCommitSha:COMMIT,createdAt:"2026-09-30T20:00:00.000Z"});const pair=generateKeyPairSync("ed25519");const public_key_pem=pair.publicKey.export({format:"pem",type:"spki"}).toString();const private_key_pem=pair.privateKey.export({format:"pem",type:"pkcs8"}).toString();const trusted_key=createTrustedAuditorKey({key_id:"quality-key-1",auditor_id:"goodle-independent-quality-auditor",public_key_pem});let key_registry=createTrustedAuditorKeyRegistry();key_registry=registerTrustedAuditorKey({registry:key_registry,key:trusted_key});const signed_attestation=createSignedIndependentQualityAttestation({quality_attestation,quality_report,report_sha256,trusted_key,key_registry,private_key_pem,expected_commit_sha:COMMIT});return{quality_report,report_sha256,quality_attestation,pair,trusted_key,key_registry,private_key_pem,signed_attestation};}
describe("M72 Signed Independent Quality Attestation",()=>{it("signs and verifies M71 with an active registry key",()=>{const f=fixture();expect(verifySignedIndependentQualityAttestation({...f,expected_commit_sha:COMMIT}).valid).toBe(true)});it("detects signature tampering",()=>{const f=fixture();const bad={...f.signed_attestation,signature_base64:Buffer.from("tampered").toString("base64")};const v=verifySignedIndependentQualityAttestation({...f,signed_attestation:bad,expected_commit_sha:COMMIT});expect(v.valid).toBe(false);expect(v.reasons).toContain("SIGNED_QUALITY_SIGNATURE_INVALID")});it("keeps historical proof valid after later key rotation",()=>{const f=fixture();const nextPair=generateKeyPairSync("ed25519");const next=createTrustedAuditorKey({key_id:"quality-key-2",auditor_id:f.trusted_key.auditor_id,public_key_pem:nextPair.publicKey.export({format:"pem",type:"spki"}).toString()});const later=rotateTrustedAuditorKey({registry:f.key_registry,current_key:f.trusted_key,next_key:next,reason_code:"scheduled-rotation"});const v=verifySignedIndependentQualityAttestation({...f,key_registry:later,expected_commit_sha:COMMIT});expect(v.valid).toBe(true)});it("rejects creation with a revoked key",()=>{const f=fixture();const revoked=revokeTrustedAuditorKey({registry:f.key_registry,key:f.trusted_key,reason_code:"compromised"});expect(()=>createSignedIndependentQualityAttestation({...f,key_registry:revoked,expected_commit_sha:COMMIT})).toThrow("SIGNED_QUALITY_KEY_NOT_ACTIVE")});it("detects registry snapshot tampering",()=>{const f=fixture();const bad={...f.signed_attestation,key_registry_snapshot_hash:"0".repeat(64)};const v=verifySignedIndependentQualityAttestation({...f,signed_attestation:bad,expected_commit_sha:COMMIT});expect(v.valid).toBe(false);expect(v.reasons).toContain("SIGNED_QUALITY_REGISTRY_SNAPSHOT_INVALID")});});
