import { useState } from "react";
import { Previa } from "./componentes/Previa";
import { EditorIntencao } from "./componentes/EditorIntencao";
import { PainelComponentes, type SecaoGoodStudio } from "./componentes/PainelComponentes";
import { ChronicleProvider } from "./chronicle/ChronicleStore";
import { ManifestationRegistryProvider } from "./chronicle/ManifestationRegistry";
import { createStudioDraft, updateStudioDraft } from "./StudioDraftState";
import { GoodleButton, GoodleCommandBar, GoodleMark, GoodleRunResult, GoodleSemanticIcon, GoodleStatus, type GoodleRunState } from "../ui/goodle";
import {compileManifestationArtifact,type ManifestationArtifact} from "../runtime/ManifestationArtifact";
import {ManifestationResult} from "../runtime/ManifestationResult";
type Espaco="studio"|"funspace";
export function EstudioGoodle(){
 const[draft,setDraft]=useState(createStudioDraft),[espaco,setEspaco]=useState<Espaco>("studio"),[secao,setSecao]=useState<SecaoGoodStudio>("Início"),[estado,setEstado]=useState("Pronto para criar"),[ultimaIntencao,setUltimaIntencao]=useState(""),[runState,setRunState]=useState<GoodleRunState>("idle"),[resultado,setResultado]=useState(""),[artifact,setArtifact]=useState<ManifestationArtifact|null>(null);
 function criar(intencao:string){setEstado("Processando intenção…");setUltimaIntencao(intencao);setRunState("idle");setResultado("");setArtifact(null);setDraft(c=>updateStudioDraft(c,{naturalIntent:intencao}));window.setTimeout(()=>setEstado("Intenção aplicada ao workspace local"),180)}
 function executar(){const intent=(ultimaIntencao||draft.naturalIntent).trim();if(!intent){setEstado("Adicione uma intenção antes de executar");setRunState("error");return}setRunState("running");setArtifact(null);setEstado("Executando intenção…");window.setTimeout(()=>{const next=compileManifestationArtifact(intent);setArtifact(next);setResultado(intent);setRunState("manifested");setEstado("Manifestação jogável pronta")},500)}
 return <ChronicleProvider><ManifestationRegistryProvider><main className="estudio">
 <header className="cabecalho"><div className="marca"><GoodleMark/><div className="marca__word"><strong>goodle<sup>®</sup></strong><span>CREATE ANYTHING</span></div></div><GoodleCommandBar placeholder="Crie qualquer coisa..." onSubmit={criar}/><div className="acoes-cabecalho"><button className="icon-action" type="button" aria-label="Configurações">⚙</button><GoodleButton semantic="action" type="button" onClick={executar} disabled={runState==="running"}><GoodleSemanticIcon tone="action"/> {runState==="running"?"Executando…":"Executar"}</GoodleButton><span className="avatar"><GoodleMark/></span></div></header>
 <div className="browser-modebar"><button className={`browser-mode${espaco==="studio"?" browser-mode--active":""}`} onClick={()=>setEspaco("studio")}>Projeto</button><button className={`browser-mode${espaco==="funspace"?" browser-mode--active":""}`} onClick={()=>setEspaco("funspace")}>FunSpace</button><span className="browser-mode-hint"><GoodleStatus label={estado} tone={runState==="manifested"?"manifestation":runState==="running"?"action":runState==="error"?"error":"idle"}/></span></div>
 {espaco==="studio"?<section className="grade-estudio"><PainelComponentes ativa={secao} onSelect={n=>{setSecao(n);setEstado(`${n} aberto`)}}/><div className="workspace-stack"><div className="workspace-context"><span>Canvas · {secao}</span>{ultimaIntencao&&<strong><GoodleSemanticIcon tone="intention"/> {ultimaIntencao}</strong>}</div><Previa/><GoodleRunResult state={runState} title={runState==="manifested"?"Manifestação jogável":undefined} detail={runState==="manifested"?resultado:undefined}/>{artifact&&<ManifestationResult artifact={artifact}/>}</div><EditorIntencao oldRewrite={draft.oldRewrite} naturalIntent={draft.naturalIntent} onOldRewriteChange={v=>setDraft(c=>updateStudioDraft(c,{oldRewrite:v}))} onNaturalIntentChange={v=>setDraft(c=>updateStudioDraft(c,{naturalIntent:v}))}/></section>:<section className="funspace-workspace"><div className="funspace-orbit"><GoodleMark/></div><span className="funspace-kicker">FUNSPACE</span><h1>Crie, explore e teste experiências.</h1><p>Um espaço vivo para experimentar ideias antes de manifestá-las no projeto.</p><div className="funspace-actions"><GoodleButton semantic="manifestation" onClick={()=>setEspaco("studio")}><GoodleSemanticIcon tone="manifestation"/> Manifestar</GoodleButton><GoodleButton semantic="intention" onClick={()=>setEstado("FunSpace pronto")}><GoodleSemanticIcon tone="intention"/> Nova experiência</GoodleButton></div>{ultimaIntencao&&<div className="funspace-intent"><small>INTENÇÃO</small><strong>{ultimaIntencao}</strong></div>}</section>}
 <footer className="barra-status"><GoodleStatus label="Goodle Runtime" tone={runState==="manifested"?"manifestation":runState==="running"?"action":"idle"}/><span>{espaco==="studio"?`Canvas · ${secao}`:"FunSpace"}</span><span>React + Phaser</span></footer>
 </main></ManifestationRegistryProvider></ChronicleProvider>
}
