import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { sha256File } from "./lib/independent-quality-attestation.mjs";
import { createSignedIndependentQualityAttestation, verifySignedIndependentQualityAttestation } from "../src/nucleo/lineage/SignedIndependentQualityAttestation";

function arg(name:string,fallback?:string){const i=process.argv.indexOf(name);return i>=0&&process.argv[i+1]?process.argv[i+1]:fallback}
function readJson(path:string){return JSON.parse(readFileSync(resolve(path),"utf8"))}
function gitHead(){return execFileSync("git",["rev-parse","HEAD"],{encoding:"utf8"}).trim()}
const mode=process.argv[2];if(!["create","verify"].includes(mode)){console.error("Usage: tsx scripts/signed-independent-quality-attestation.ts <create|verify> --report <json> --attestation <json> --trusted-key <json> --registry <json> [--private-key <pem> --out <json>|--signed <json>]");process.exit(2)}
const reportPath=arg("--report",".goodle/quality/independent-validation.json")!;const attestationPath=arg("--attestation",".goodle/quality/independent-attestation.json")!;const trustedKeyPath=arg("--trusted-key")!;const registryPath=arg("--registry")!;if(!trustedKeyPath||!registryPath){console.error("--trusted-key and --registry are required");process.exit(2)}
const quality_report=readJson(reportPath),quality_attestation=readJson(attestationPath),trusted_key=readJson(trustedKeyPath),key_registry=readJson(registryPath),report_sha256=sha256File(resolve(reportPath)),expected_commit_sha=arg("--commit",gitHead());
if(mode==="create"){const privateKeyPath=arg("--private-key");if(!privateKeyPath){console.error("--private-key is required for create");process.exit(2)}const out=resolve(arg("--out",".goodle/quality/signed-independent-attestation.json")!);const signed_attestation=createSignedIndependentQualityAttestation({quality_attestation,quality_report,report_sha256,trusted_key,key_registry,private_key_pem:readFileSync(resolve(privateKeyPath),"utf8"),expected_commit_sha});const verification=verifySignedIndependentQualityAttestation({signed_attestation,quality_attestation,quality_report,report_sha256,trusted_key,key_registry,expected_commit_sha});if(!verification.valid){console.error("Signed independent quality self-verification: FAIL",verification.reasons);process.exit(1)}mkdirSync(dirname(out),{recursive:true});writeFileSync(out,JSON.stringify(signed_attestation,null,2)+"\n");console.log("Signed independent quality attestation: PASS");console.log("Signed attestation:",out);console.log("Signed attestation ID:",signed_attestation.signed_attestation_id);process.exit(0)}
const signedPath=arg("--signed",".goodle/quality/signed-independent-attestation.json")!;const signed_attestation=readJson(signedPath);const verification=verifySignedIndependentQualityAttestation({signed_attestation,quality_attestation,quality_report,report_sha256,trusted_key,key_registry,expected_commit_sha});console.log("Signed independent quality attestation verification:",verification.valid?"PASS":"FAIL");if(!verification.valid)console.error(verification.reasons.join("\n"));process.exit(verification.valid?0:1);
